### ISSUE TITLE
Dark mode is missing

### ISSUE THREAD

**Issue by Neustradamus** [ugetdm/uget#20]
Dark mode is missing

**Comment by MichaelTunnell** [comment]
It's not, this is controlled by your system theme. uGet automatically adjusts itself according to your global theme so if you want a dark theme just set your computer to use a global dark theme and uGet will use it.

**Comment by hans-thomas** [comment]
No sir, it doesn't.

[screen](https://ir11.uploadboy.com/d/aus1r5bkkrbq/ubnkas7bjdgrhfoh3qug7w6cxwfz2ntupuwyeuiqox472qexyxtx5yn5heu6joxzeuko5npx/Screenshot_20210711_151837.png)

os: manjaro
theme: Breeze Dark

**Comment by Neustradamus** [comment]
@MichaelTunnell: Can you reopen it?
It is not solved!

**Comment by Yolakalemowa** [comment]
still waiting lol...

would be great to have a dark theme

**Comment by Neustradamus** [comment]
The development is down since a very long time, all code has been imported from SF here:
- https://github.com/urlget

**Comment by Yolakalemowa** [comment]
@Neustradamus 

oh shoot... no longer supported? any other good alternatives you can point me to?

**Comment by Neustradamus** [comment]
I think that a new team must to work on it...

**Comment by MichaelTunnell** [comment]
@Neustradamus
the last release of uGet for desktop was in mid 2021 so its not super active but its not gone. The SF to GitHub is just a mirror its not a departure. The main dev C.H. prefers to use SF so he does.

@hans-thomas

This requires GTK3 dark so in Plasma you need to specific adjust the GTK Settings in the System Settings. In here you need to tell it to use a dark theme. Unforutnately GTK is not dark mode friendly in general.

![edit-gtk-theme-in-kde-system-settings](https://user-images.githubusercontent.com/1056731/154825283-d13cab34-11ce-449f-aace-c1705c95c166.png)

**Comment by Neustradamus** [comment]
GitHub is up-to-date here: https://github.com/urlget/uget2.

Sourceforge:
- https://sourceforge.net/p/urlget/uget2/ci/master/tree/ -> https://sourceforge.net/p/urlget/uget2/ci/6ee0ed24ae1b63d7874ad9713300a07b7b60c638/log/?path= (2020-02-27 01:47:04)
- https://sourceforge.net/p/urlget/uget2/ci/Branch_uGet-2.0/tree/ -> https://sourceforge.net/p/urlget/uget2/ci/817492ba0895eb2da83c4e827c84aba50aa3f4d2/log/?path=
- https://sourceforge.net/p/urlget/uget2/ci/uGet-2.0.x/tree/ -> https://sourceforge.net/p/urlget/uget2/ci/0a2866518b21a5251a8689848e8b823e394fb440/log/?path=

Here: https://sourceforge.net/projects/urlget/files/uget%20%28stable%29/2.2.3/
uGet 2.2.3: (2020-01-01)
1. add parser for YouTube recently changed field.

**Comment by MichaelTunnell** [comment]
the 2021 was a fix for the windows version. I did say its not active. but inactive and down are much different. Development is not up to me either way.

**Comment by Neustradamus** [comment]
This ticket must be reopen.
