### ISSUE TITLE
Website: certificate expired

### ISSUE THREAD

**Issue by bayasdev** [ugetdm/uget#32]
The SSL certificate for https://ugetdm.com expired on October 7th

**Comment by bayasdev** [comment]
Fixed

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/ugetdm/uget/issues/9

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/ugetdm/uget/issues/9
- https://github.com/ugetdm/uget/issues/32
- https://github.com/ugetdm/uget/issues/44
- https://github.com/ugetdm/uget/issues/53
