### ISSUE TITLE
Path Register.exe detected as Malware.AI.1877196664 on Malwarebytes

### ISSUE THREAD

**Issue by AnimMouse** [ugetdm/uget#35]
VirusTotal:
[Path Register.exe](https://www.virustotal.com/gui/file/37d2281bbbfdd1c5782cbfc182253f47e30b76511fa04bba6a8616ab7cfb66d7/detection)
[uget-2.2.3-1-win32+gtk3.7z](https://www.virustotal.com/gui/file/169c3e638ddf59212d2849bc320796d86cdd6426596ee913900e9bac28928a80/detection)
[uget-2.2.1-win32+gtk3.7z](https://www.virustotal.com/gui/file/a722bd02a6d77ac24b8bb7d1b3a6c7f37ca4dbab40859264b1e50dedbcda584a/detection)
[uget-2.2.3-2-win32+gtk3.7z](https://www.virustotal.com/gui/file/6536d4c0eee0098cef8f6d88fde0b3474e078b40599a881e8ba0e7805f6dc50f/detection)

**Comment by Maziar123** [comment]
yes
it have some security problem in linux :
[(https://github.com/ugetdm/uget/issues/36)]

**Comment by Neustradamus** [comment]
Any news?

**Comment by AnimMouse** [comment]
Path Register.exe is now undetected on Malwarebytes as of 2021-06-16 15:09:49
uget-2.2.3-1-win32+gtk3.7z is now MachineLearning/Anomalous.93% on Malwarebytes as of 2021-06-07 07:01:31 UTC
uget-2.2.1-win32+gtk3.7z is now MachineLearning/Anomalous.94% on Malwarebytes as of 2021-07-10 17:48:53 UTC
uget-2.2.3-2-win32+gtk3.7z is now MachineLearning/Anomalous.93% on Malwarebytes as of 2021-07-10 03:09:52 UTC

**Comment by Neustradamus** [comment]
uGet is now on GitHub (unofficial): https://github.com/urlget

**Comment by Neustradamus** [comment]
@AnimMouse: It has been solved? I do not think.

**Comment by AnimMouse** [comment]
@Neustradamus All files on VirusTotal are now undetected by Malwarebytes of 2023-12-01.
