### ISSUE TITLE
Username & Password Manager?

### ISSUE THREAD

**Issue by rayman3003** [ugetdm/uget#37]
I can't find a place in settings, to save username & password for the password-required websites.

Could u please add a username & password option in the settings? (username & password get saved there forever, So we won't need to type username & password each time)

**Comment by MichaelTunnell** [comment]
This is already possible by editing the preferences of a category so just create a new category for the website you want to save the login for and insert the info there

**Comment by rayman3003** [comment]
Yeap, that's correct. Please close this issue. :P

**Comment by MichaelTunnell** [comment]
Glad to hear this works for you. :+1:
